providers:
  openai:
    packages: ["openai"]
    modules: ["openai"]
    env_vars: ["OPENAI_API_KEY"]
    models:
      - gpt-4o-mini
      - gpt-4o
      - gpt-4.1-mini
      - gpt-4.1
      - gpt-3.5-turbo
    note: ""
  anthropic:
    packages: ["anthropic"]
    modules: ["anthropic"]
    env_vars: ["ANTHROPIC_API_KEY"]
    models:
      - claude-3-haiku-20240307
      - claude-3-sonnet-20240229
      - claude-3-opus-20240229
    note: ""
  gemini:
    packages: ["google-generativeai"]
    modules: ["google.generativeai"]
    env_vars: ["GEMINI_API_KEY", "GOOGLE_API_KEY"]
    models:
      - gemini-2.5-flash
      - gemini-2.5-flash-lite
      - gemini-pro
      - gemini-1.5-pro-latest
    note: "無料枠では gemini-2.5-flash / gemini-2.5-flash-lite を利用できます。"
